[tool.poetry]
name = "sqlalchemy-galaxy-schema"
version = "0.1.0"
description = ""
authors = ["Daniel Bradburn <moagstar@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
sqlalchemy = "^1"
toolz = "^0.11.1"
funcoperators = "^1.1.3"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pytest = "^6.1.0"
sqlparse = "^0.3.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
