#!/usr/bin/env python3

# publish a release

from subprocess import check_output
from shlex import split
import sys

MAIN_BRANCH = "main"

_ = lambda x: check_output(split(x)).decode().strip()
header = lambda x: print("\n" + f" {x} ".center(70, "="), end="\n\n")

branch = _("git rev-parse --symbolic-full-name --abbrev-ref HEAD")
assert branch == MAIN_BRANCH, branch

status = _("git status --porcelain")
assert status == "", status

# run tests (don't publish anything that is failing)
_("tools/qa")

# publish and create tag
_("git pull")
_("poetry build")
_("poetry publish")
version = _("poetry version --short")
_(f"git tag {version}")
_(f'git push origin "{version}"')
