#!/usr/bin/env python3
# std
import sys
from pprint import pprint
from subprocess import call
from shlex import split
# 3rd party
from toolz import valfilter, identity

# run all quality assurance checks, report errors

results = []

_ = lambda x: results.append((x, call(split(x))))
header = lambda x: print('\n' + f' {x} '.center(70, '='), end='\n\n')

header('lint')
_('isort star_alchemy tests --check')
_('black star_alchemy tests --check')

header('type check')
_('mypy star_alchemy')

header('unit tests')
_('python -m unittest discover tests')

if (failed := valfilter(identity, dict(results))):
    print('\nFAILED COMMANDS:\n')
    pprint(failed)
    sys.exit(1)
